# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nick/Documents/Programs/dungeonbreath

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nick/Documents/Programs/dungeonbreath

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nick/Documents/Programs/dungeonbreath/CMakeFiles /home/nick/Documents/Programs/dungeonbreath/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nick/Documents/Programs/dungeonbreath/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dungeonbreath

# Build rule for target.
dungeonbreath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dungeonbreath
.PHONY : dungeonbreath

# fast build rule for target.
dungeonbreath/fast:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/build
.PHONY : dungeonbreath/fast

src/Actor.o: src/Actor.cpp.o

.PHONY : src/Actor.o

# target to build an object file
src/Actor.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Actor.cpp.o
.PHONY : src/Actor.cpp.o

src/Actor.i: src/Actor.cpp.i

.PHONY : src/Actor.i

# target to preprocess a source file
src/Actor.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Actor.cpp.i
.PHONY : src/Actor.cpp.i

src/Actor.s: src/Actor.cpp.s

.PHONY : src/Actor.s

# target to generate assembly for a file
src/Actor.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Actor.cpp.s
.PHONY : src/Actor.cpp.s

src/Animation.o: src/Animation.cpp.o

.PHONY : src/Animation.o

# target to build an object file
src/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Animation.cpp.o
.PHONY : src/Animation.cpp.o

src/Animation.i: src/Animation.cpp.i

.PHONY : src/Animation.i

# target to preprocess a source file
src/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Animation.cpp.i
.PHONY : src/Animation.cpp.i

src/Animation.s: src/Animation.cpp.s

.PHONY : src/Animation.s

# target to generate assembly for a file
src/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Animation.cpp.s
.PHONY : src/Animation.cpp.s

src/Button.o: src/Button.cpp.o

.PHONY : src/Button.o

# target to build an object file
src/Button.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Button.cpp.o
.PHONY : src/Button.cpp.o

src/Button.i: src/Button.cpp.i

.PHONY : src/Button.i

# target to preprocess a source file
src/Button.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Button.cpp.i
.PHONY : src/Button.cpp.i

src/Button.s: src/Button.cpp.s

.PHONY : src/Button.s

# target to generate assembly for a file
src/Button.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Button.cpp.s
.PHONY : src/Button.cpp.s

src/ButtonGroup.o: src/ButtonGroup.cpp.o

.PHONY : src/ButtonGroup.o

# target to build an object file
src/ButtonGroup.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/ButtonGroup.cpp.o
.PHONY : src/ButtonGroup.cpp.o

src/ButtonGroup.i: src/ButtonGroup.cpp.i

.PHONY : src/ButtonGroup.i

# target to preprocess a source file
src/ButtonGroup.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/ButtonGroup.cpp.i
.PHONY : src/ButtonGroup.cpp.i

src/ButtonGroup.s: src/ButtonGroup.cpp.s

.PHONY : src/ButtonGroup.s

# target to generate assembly for a file
src/ButtonGroup.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/ButtonGroup.cpp.s
.PHONY : src/ButtonGroup.cpp.s

src/ConfigLoader.o: src/ConfigLoader.cpp.o

.PHONY : src/ConfigLoader.o

# target to build an object file
src/ConfigLoader.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/ConfigLoader.cpp.o
.PHONY : src/ConfigLoader.cpp.o

src/ConfigLoader.i: src/ConfigLoader.cpp.i

.PHONY : src/ConfigLoader.i

# target to preprocess a source file
src/ConfigLoader.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/ConfigLoader.cpp.i
.PHONY : src/ConfigLoader.cpp.i

src/ConfigLoader.s: src/ConfigLoader.cpp.s

.PHONY : src/ConfigLoader.s

# target to generate assembly for a file
src/ConfigLoader.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/ConfigLoader.cpp.s
.PHONY : src/ConfigLoader.cpp.s

src/ConsoleLogger.o: src/ConsoleLogger.cpp.o

.PHONY : src/ConsoleLogger.o

# target to build an object file
src/ConsoleLogger.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/ConsoleLogger.cpp.o
.PHONY : src/ConsoleLogger.cpp.o

src/ConsoleLogger.i: src/ConsoleLogger.cpp.i

.PHONY : src/ConsoleLogger.i

# target to preprocess a source file
src/ConsoleLogger.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/ConsoleLogger.cpp.i
.PHONY : src/ConsoleLogger.cpp.i

src/ConsoleLogger.s: src/ConsoleLogger.cpp.s

.PHONY : src/ConsoleLogger.s

# target to generate assembly for a file
src/ConsoleLogger.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/ConsoleLogger.cpp.s
.PHONY : src/ConsoleLogger.cpp.s

src/DeviceButton.o: src/DeviceButton.cpp.o

.PHONY : src/DeviceButton.o

# target to build an object file
src/DeviceButton.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/DeviceButton.cpp.o
.PHONY : src/DeviceButton.cpp.o

src/DeviceButton.i: src/DeviceButton.cpp.i

.PHONY : src/DeviceButton.i

# target to preprocess a source file
src/DeviceButton.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/DeviceButton.cpp.i
.PHONY : src/DeviceButton.cpp.i

src/DeviceButton.s: src/DeviceButton.cpp.s

.PHONY : src/DeviceButton.s

# target to generate assembly for a file
src/DeviceButton.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/DeviceButton.cpp.s
.PHONY : src/DeviceButton.cpp.s

src/FontMap.o: src/FontMap.cpp.o

.PHONY : src/FontMap.o

# target to build an object file
src/FontMap.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/FontMap.cpp.o
.PHONY : src/FontMap.cpp.o

src/FontMap.i: src/FontMap.cpp.i

.PHONY : src/FontMap.i

# target to preprocess a source file
src/FontMap.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/FontMap.cpp.i
.PHONY : src/FontMap.cpp.i

src/FontMap.s: src/FontMap.cpp.s

.PHONY : src/FontMap.s

# target to generate assembly for a file
src/FontMap.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/FontMap.cpp.s
.PHONY : src/FontMap.cpp.s

src/GameScene.o: src/GameScene.cpp.o

.PHONY : src/GameScene.o

# target to build an object file
src/GameScene.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/GameScene.cpp.o
.PHONY : src/GameScene.cpp.o

src/GameScene.i: src/GameScene.cpp.i

.PHONY : src/GameScene.i

# target to preprocess a source file
src/GameScene.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/GameScene.cpp.i
.PHONY : src/GameScene.cpp.i

src/GameScene.s: src/GameScene.cpp.s

.PHONY : src/GameScene.s

# target to generate assembly for a file
src/GameScene.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/GameScene.cpp.s
.PHONY : src/GameScene.cpp.s

src/Hero.o: src/Hero.cpp.o

.PHONY : src/Hero.o

# target to build an object file
src/Hero.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Hero.cpp.o
.PHONY : src/Hero.cpp.o

src/Hero.i: src/Hero.cpp.i

.PHONY : src/Hero.i

# target to preprocess a source file
src/Hero.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Hero.cpp.i
.PHONY : src/Hero.cpp.i

src/Hero.s: src/Hero.cpp.s

.PHONY : src/Hero.s

# target to generate assembly for a file
src/Hero.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Hero.cpp.s
.PHONY : src/Hero.cpp.s

src/Input.o: src/Input.cpp.o

.PHONY : src/Input.o

# target to build an object file
src/Input.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Input.cpp.o
.PHONY : src/Input.cpp.o

src/Input.i: src/Input.cpp.i

.PHONY : src/Input.i

# target to preprocess a source file
src/Input.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Input.cpp.i
.PHONY : src/Input.cpp.i

src/Input.s: src/Input.cpp.s

.PHONY : src/Input.s

# target to generate assembly for a file
src/Input.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Input.cpp.s
.PHONY : src/Input.cpp.s

src/Logger.o: src/Logger.cpp.o

.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i

.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s

.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/MainMenuScene.o: src/MainMenuScene.cpp.o

.PHONY : src/MainMenuScene.o

# target to build an object file
src/MainMenuScene.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/MainMenuScene.cpp.o
.PHONY : src/MainMenuScene.cpp.o

src/MainMenuScene.i: src/MainMenuScene.cpp.i

.PHONY : src/MainMenuScene.i

# target to preprocess a source file
src/MainMenuScene.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/MainMenuScene.cpp.i
.PHONY : src/MainMenuScene.cpp.i

src/MainMenuScene.s: src/MainMenuScene.cpp.s

.PHONY : src/MainMenuScene.s

# target to generate assembly for a file
src/MainMenuScene.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/MainMenuScene.cpp.s
.PHONY : src/MainMenuScene.cpp.s

src/MusicManager.o: src/MusicManager.cpp.o

.PHONY : src/MusicManager.o

# target to build an object file
src/MusicManager.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/MusicManager.cpp.o
.PHONY : src/MusicManager.cpp.o

src/MusicManager.i: src/MusicManager.cpp.i

.PHONY : src/MusicManager.i

# target to preprocess a source file
src/MusicManager.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/MusicManager.cpp.i
.PHONY : src/MusicManager.cpp.i

src/MusicManager.s: src/MusicManager.cpp.s

.PHONY : src/MusicManager.s

# target to generate assembly for a file
src/MusicManager.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/MusicManager.cpp.s
.PHONY : src/MusicManager.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/SpriteSet.o: src/SpriteSet.cpp.o

.PHONY : src/SpriteSet.o

# target to build an object file
src/SpriteSet.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/SpriteSet.cpp.o
.PHONY : src/SpriteSet.cpp.o

src/SpriteSet.i: src/SpriteSet.cpp.i

.PHONY : src/SpriteSet.i

# target to preprocess a source file
src/SpriteSet.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/SpriteSet.cpp.i
.PHONY : src/SpriteSet.cpp.i

src/SpriteSet.s: src/SpriteSet.cpp.s

.PHONY : src/SpriteSet.s

# target to generate assembly for a file
src/SpriteSet.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/SpriteSet.cpp.s
.PHONY : src/SpriteSet.cpp.s

src/TextureMap.o: src/TextureMap.cpp.o

.PHONY : src/TextureMap.o

# target to build an object file
src/TextureMap.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/TextureMap.cpp.o
.PHONY : src/TextureMap.cpp.o

src/TextureMap.i: src/TextureMap.cpp.i

.PHONY : src/TextureMap.i

# target to preprocess a source file
src/TextureMap.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/TextureMap.cpp.i
.PHONY : src/TextureMap.cpp.i

src/TextureMap.s: src/TextureMap.cpp.s

.PHONY : src/TextureMap.s

# target to generate assembly for a file
src/TextureMap.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/TextureMap.cpp.s
.PHONY : src/TextureMap.cpp.s

src/TileSet.o: src/TileSet.cpp.o

.PHONY : src/TileSet.o

# target to build an object file
src/TileSet.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/TileSet.cpp.o
.PHONY : src/TileSet.cpp.o

src/TileSet.i: src/TileSet.cpp.i

.PHONY : src/TileSet.i

# target to preprocess a source file
src/TileSet.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/TileSet.cpp.i
.PHONY : src/TileSet.cpp.i

src/TileSet.s: src/TileSet.cpp.s

.PHONY : src/TileSet.s

# target to generate assembly for a file
src/TileSet.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/TileSet.cpp.s
.PHONY : src/TileSet.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/dungeonbreath.dir/build.make CMakeFiles/dungeonbreath.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... dungeonbreath"
	@echo "... edit_cache"
	@echo "... src/Actor.o"
	@echo "... src/Actor.i"
	@echo "... src/Actor.s"
	@echo "... src/Animation.o"
	@echo "... src/Animation.i"
	@echo "... src/Animation.s"
	@echo "... src/Button.o"
	@echo "... src/Button.i"
	@echo "... src/Button.s"
	@echo "... src/ButtonGroup.o"
	@echo "... src/ButtonGroup.i"
	@echo "... src/ButtonGroup.s"
	@echo "... src/ConfigLoader.o"
	@echo "... src/ConfigLoader.i"
	@echo "... src/ConfigLoader.s"
	@echo "... src/ConsoleLogger.o"
	@echo "... src/ConsoleLogger.i"
	@echo "... src/ConsoleLogger.s"
	@echo "... src/DeviceButton.o"
	@echo "... src/DeviceButton.i"
	@echo "... src/DeviceButton.s"
	@echo "... src/FontMap.o"
	@echo "... src/FontMap.i"
	@echo "... src/FontMap.s"
	@echo "... src/GameScene.o"
	@echo "... src/GameScene.i"
	@echo "... src/GameScene.s"
	@echo "... src/Hero.o"
	@echo "... src/Hero.i"
	@echo "... src/Hero.s"
	@echo "... src/Input.o"
	@echo "... src/Input.i"
	@echo "... src/Input.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/MainMenuScene.o"
	@echo "... src/MainMenuScene.i"
	@echo "... src/MainMenuScene.s"
	@echo "... src/MusicManager.o"
	@echo "... src/MusicManager.i"
	@echo "... src/MusicManager.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/SpriteSet.o"
	@echo "... src/SpriteSet.i"
	@echo "... src/SpriteSet.s"
	@echo "... src/TextureMap.o"
	@echo "... src/TextureMap.i"
	@echo "... src/TextureMap.s"
	@echo "... src/TileSet.o"
	@echo "... src/TileSet.i"
	@echo "... src/TileSet.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

